apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ai-gateway-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - envoy-gateway-system
  selector:
    matchLabels:
      app: envoy-proxy-metrics
  endpoints:
    - port: aigw-admin
      path: /metrics
      interval: 15s
