apiVersion: v1
kind: Service
metadata:
  name: envoy-proxy-metrics
  namespace: envoy-gateway-system
  labels:
    app: envoy-proxy-metrics
spec:
  selector:
    gateway.envoyproxy.io/owning-gateway-name: ai-gateway
  ports:
    - name: metrics
      port: 19001
      targetPort: 19001
    - name: aigw-admin
      port: 1064
      targetPort: 1064
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: envoy-proxy-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - envoy-gateway-system
  selector:
    matchLabels:
      app: envoy-proxy-metrics
  endpoints:
    - port: metrics
      path: /stats/prometheus
      interval: 15s
