apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vllm-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - beta
  selector:
    matchExpressions:
      - key: serving.kserve.io/inferenceservice
        operator: Exists
  endpoints:
    - port: http-serving
      path: /metrics
      interval: 15s
