apiVersion: v1
kind: ConfigMap
metadata:
  name: inferenceservice-config
  namespace: kserve
data:
  storageInitializer: |-
    {
      "cpuRequest": "100m",
      "cpuLimit": "4",
      "memoryRequest": "100Mi",
      "memoryLimit": "24Gi"
    }
