apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceServiceConfig
metadata:
  name: llm-inference-service-config-model
  namespace: beta
spec:
  model:
    uri: hf://google/gemma-4-31B-it-qat-w4a16-ct
    name: google/gemma-4-31B-it-qat-w4a16-ct
