apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceServiceConfig
metadata:
  name: llm-inference-service-config-model
  namespace: beta
spec:
  model:
    uri: hf://Qwen/Qwen2.5-32B-Instruct-AWQ
    name: Qwen/Qwen2.5-32B-Instruct-AWQ
