apiVersion: serving.kserve.io/v1alpha2
kind: LLMInferenceServiceConfig
metadata:
  name: llm-d-vllm-template
  namespace: beta
spec:
  router:
    scheduler:
      config:
        inline:
          scoringRules:
            prefix-cache:
              weight: 2.0
            load-aware:
              weight: 1.0
          picker:
            policy: max-score
          cache:
            enabled: true
            maxCacheCapacity: 10000
          timeout: "300s"
  template:
    imagePullSecrets:
      - name: registry-credentials
    containers:
      - name: main
        image: docker-registry.yacodata.com/kserve-vllm-qwen:0.1
        imagePullPolicy: Always
        args:
          - --model
          - Qwen/Qwen2.5-7B-Instruct
