apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceServiceConfig
metadata:
  name: llm-d-vllm-template
  namespace: beta
spec:
  router:
    scheduler:
      endpointPicker:
        plugins:
          - name: prefix-cache-scorer
            weight: 2.0
          - name: load-aware-scorer
            weight: 1.0
        picker:
          policy: max-score
    route:
      cache:
        enabled: true
        maxCacheCapacity: 10000
      timeout: 300s
  template:
    imagePullSecrets:
      - name: registry-credentials
    containers:
      - name: main
        image: docker-registry.yacodata.com/kserve-vllm-qwen:0.1
        imagePullPolicy: Always
        args:
          - --model
          - Qwen/Qwen2.5-7B-Instruct
