apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextchat
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextchat
  template:
    metadata:
      labels:
        app: nextchat
    spec:
      containers:
        - name: nextchat
          image: yidadaa/chatgpt-next-web:latest
          ports:
            - containerPort: 3000
          env:
            - name: BASE_URL
              value: "https://llm.yacodata.com"
            - name: CUSTOM_MODELS
              value: "casperhansen/deepseek-r1-distill-qwen-14b-awq"
            - name: CODE
              valueFrom:
                secretKeyRef:
                  name: nextchat-secret
                  key: code
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 500m
      volumes: []
