apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: mistral7b-inferencepool-backend
  namespace: omega
spec:
  endpoints:
    - fqdn:
        hostname: mistral7b-kserve-workload-svc.omega.svc.cluster.local
        port: 8000
---
apiVersion: aigateway.envoyproxy.io/v1beta1
kind: AIServiceBackend
metadata:
  name: mistral7b-backend
  namespace: omega
spec:
  backendRef:
    group: gateway.envoyproxy.io
    kind: Backend
    name: mistral7b-inferencepool-backend
  schema:
    name: OpenAI
    version: v1
