apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: llm-server-inferencepool-backend
  namespace: beta
spec:
  endpoints:
    - fqdn:
        hostname: llm-server-kserve-workload-svc.beta.svc.cluster.local
        port: 8000
---
apiVersion: aigateway.envoyproxy.io/v1beta1
kind: AIServiceBackend
metadata:
  name: llm-server-backend
  namespace: beta
spec:
  backendRef:
    group: gateway.envoyproxy.io
    kind: Backend
  name: llm-server-inferencepool-backend
  schema:
    name: OpenAI
    version: v1



backend.gateway.envoyproxy.io/llm-server-inferencepool-backend unchanged
Error from server (BadRequest): error when creating "/root/self-host-llm-ai-inference/case_beta/envoy-ai-gateway/backend.yaml": AIServiceBackend in version "v1beta1" cannot be handled as a AIServiceBackend: strict decoding error: unknown field "spec.name"