apiVersion: inference.envoy.ai/v1alpha1
kind: InferencePool
metadata:
  name: qwen-pool
  namespace: beta
spec:
  selector:
    app.kubernetes.io/name: qwen-7b
  podSelector:
    matchLabels:
      app.kubernetes.io/name: qwen-7b
  failurePolicy: Fail
---
apiVersion: inference.envoy.ai/v1alpha1
kind: InferenceModel
metadata:
  name: qwen2.5-7b
  namespace: beta
spec:
  modelName: qwen2.5-7b
  poolRef:
    name: qwen-pool
