apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: deepseek-rate-limit
  namespace: beta
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: deepseek-14b-kserve-route
  rateLimit:
    type: Global
    global:
      rules:
        - clientSelectors:
            - headers:
                - name: x-ai-eg-model
                  value: casperhansen/deepseek-r1-distill-qwen-14b-awq
          limit:
            requests: 30
            unit: Minute
        - clientSelectors:
            - headers:
                - name: x-ai-eg-model
                  value: casperhansen/deepseek-r1-distill-qwen-14b-awq
          limit:
            requests: 5000
            unit: Minute
