apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: qwen-backend
  namespace: alpha
spec:
  endpoints:
    - fqdn:
        hostname: vllm-service.alpha.svc.cluster.local
        port: 8100
---
apiVersion: aigateway.envoyproxy.io/v1beta1
kind: AIServiceBackend
metadata:
  name: qwen-aiservicebackend
  namespace: alpha
spec:
  backendRef:
    group: gateway.envoyproxy.io
    kind: Backend
    name: qwen-backend
  schema:
    name: OpenAI
    version: v1
