apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: qwen14b-inferencepool-backend
  namespace: gamma
spec:
  endpoints:
    - fqdn:
        hostname: qwen14b-kserve-workload-svc.gamma.svc.cluster.local
        port: 8000
---
apiVersion: aigateway.envoyproxy.io/v1beta1
kind: AIServiceBackend
metadata:
  name: qwen14b-backend
  namespace: gamma
spec:
  backendRef:
    group: gateway.envoyproxy.io
    kind: Backend
    name: qwen14b-inferencepool-backend
  schema:
    name: OpenAI
    version: v1
