apiVersion: inference.envoy.ai/v1alpha1
kind: InferencePool
metadata:
  name: llama-pool
  namespace: gamma
spec:
  selector:
    app.kubernetes.io/name: llama-llm
  podSelector:
    matchLabels:
      app.kubernetes.io/name: llama-llm
  failurePolicy: Fail
---
apiVersion: inference.envoy.ai/v1alpha1
kind: InferenceModel
metadata:
  name: llama3-70b
  namespace: gamma
spec:
  modelName: llama3-70b
  poolRef:
    name: llama-pool
